version: '3'

services:
  gowitness:
    build: ./
    restart: unless-stopped
    environment:
      - LC_ALL=C
    command: gowitness server --address 0.0.0.0:7171 --base-path /gowitness
    volumes:
      - ./gowitness.sqlite3:/data/gowitness.sqlite3
      - ./screenshots:/data/screenshots

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 3000:443
    volumes:
      - ./nginx/gowitness.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd
      - ./nginx/ssl/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./nginx/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
